### ISSUE TITLE
issue with version 3 

### ISSUE THREAD

**Issue by MalibuKoKo** [Magisk-Modules-Repo/airaudio#3]
Just look xda's forum : https://forum.xda-developers.com/apps/magisk/module-airaudio-audio-mode-t3753580/page2

Multiple users (including me) have a problem with the new version of airaudio, i don't take the time to investigate but i think the issue come from AARSCService.apk .

Actually, i don't have tools to extract this package & understand differences with previous version...

Just for information, my phone : OnePlus One with Android Oreo (8.1)

**Comment by MalibuKoKo** [comment]
Hi @funtax,

Thanks for your quick feedback, for now i fork your repo and add a tag on previous commit (just before this issues). I zipped files in order to restore to a stable version. 
I will try your new version and give you a feedback when you will have push your fix.

**Comment by MalibuKoKo** [comment]
Hi @funtax,

Sorry, i try version from your last commit b600d1c but that don't work :-(

**Comment by funtax** [comment]
Hey @MalibuKoKo ,

oh no, thanks for the feedback.

Can you please contact me at support@airaudio.eu so we can share some logs?

Thanks in advance :-)

**Comment by MalibuKoKo** [comment]
I you want you can create another branch in order to test together your fixes

**Comment by funtax** [comment]
Issues should be solved with v5

**Comment by MalibuKoKo** [comment]
tested & approuved ...
Thanks
