### ISSUE TITLE
not a magisk module?

### ISSUE THREAD

**Issue by sainteen1** [Magisk-Modules-Repo/airaudio#7]
i failed to install it, on android 9.0 magisk v20.0
saying this zip is not a magisk module in fail-log

**Comment by funtax** [comment]
Hey @sainteen1, thanks for reporting.
Did you manually download the module, or did you download it within the Magisk Manager?
If you manually downloaded it, please delete the zip from your device and use the Magisk Manager instead and search for this module within the modules-section :)
